export enum ErrorCode {
	IncorrectUsernamePassword = 'incorrect-username-password',
	IncorrectEmailPassword = 'incorrect-email-password',
	UserNotFound = 'user-not-found',
	IncorrectPassword = 'incorrect-password',
	UserMissingPassword = 'missing-password',
	TwoFactorDisabled = 'two-factor-disabled',
	TwoFactorAlreadyEnabled = 'two-factor-already-enabled',
	TwoFactorSetupRequired = 'two-factor-setup-required',
	SecondFactorRequired = 'second-factor-required',
	IncorrectTwoFactorCode = 'incorrect-two-factor-code',
	InternalServerError = 'internal-server-error',
	NewPasswordMatchesOld = 'new-password-matches-old',
	RateLimitExceeded = 'rate-limit-exceeded',
	ThirdPartyAuthProviderEnabled = 'third-party-identity-provider-enabled',
	SocialAuthProviderRequired = 'social-identity-provider-required',
	EmailAlreadyExists = 'email-already-exists',
	UsernameAlreadyExists = 'username-already-exists',
	PhoneAlreadyExists = 'phone-already-exists',
	UserAccountLocked = 'user-account-locked',
	MissingBackupCodes = 'missing-backup-codes',
	IncorrectBackupCode = 'incorrect-backup-code',
	SlugNotAvailable = 'slug-not-available'
}
