// This file was generated by a custom prisma generator, do not edit manually.
export const IdentityProvider = {
  JWT: "JWT",
  GOOGLE: "GOOGLE",
  GITHUB: "GITHUB",
} as const;

export type IdentityProvider = (typeof IdentityProvider)[keyof typeof IdentityProvider];

export const Locale = {
  fr: "fr",
  en: "en",
} as const;

export type Locale = (typeof Locale)[keyof typeof Locale];

export const MembershipRole = {
  MEMBER: "MEMBER",
  ADMIN: "ADMIN",
  OWNER: "OWNER",
} as const;

export type MembershipRole = (typeof MembershipRole)[keyof typeof MembershipRole];
