// This file was generated by a custom prisma generator, do not edit manually.
export const AuthProvider = {
  JWT: "JWT",
  GOOGLE: "GOOGLE",
  FACEBOOK: "FACEBOOK",
} as const;

export type AuthProvider = (typeof AuthProvider)[keyof typeof AuthProvider];

export const Locale = {
  fr: "fr",
  en: "en",
} as const;

export type Locale = (typeof Locale)[keyof typeof Locale];

export const MembershipRole = {
  MEMBER: "MEMBER",
  ADMIN: "ADMIN",
  OWNER: "OWNER",
} as const;

export type MembershipRole = (typeof MembershipRole)[keyof typeof MembershipRole];

export const FeatureType = {
  RELEASE: "RELEASE",
  EXPERIMENT: "EXPERIMENT",
  OPERATIONAL: "OPERATIONAL",
  KILL_SWITCH: "KILL_SWITCH",
  PERMISSION: "PERMISSION",
} as const;

export type FeatureType = (typeof FeatureType)[keyof typeof FeatureType];

export const Visibility = {
  PUBLIC: "PUBLIC",
  PRIVATE: "PRIVATE",
} as const;

export type Visibility = (typeof Visibility)[keyof typeof Visibility];
